let a = 'hello';
console.log(a);
let b = 'owu';
console.log(b);
let c ='com';
console.log(c);
let d = 'ua';
console.log(d);
let e = +true;
console.log(e);
let f = 10;
console.log(f);
let g = +true-1000;
console.log(g);
let h = 123;
console.log(h);
let i = 3.14;
console.log(i);
let j = 2.7;
console.log(j);
let k = 16;
console.log(k);
let l = true;
console.log(l);
let m = false;
console.log(m);
